spring:
  datasource:
    url: ${vcap.services.PostgreSQL.credentials.url}
    username: ${vcap.services.PostgreSQL.credentials.username}
    password: ${vcap.services.PostgreSQL.credentials.password}

  jpa:
    hibernate:
      ddl-auto: update