spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pets
    username: postgres
    password: password
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

logging:
  level:
    com.leverx.leverxspringbootapp: INFO